<?php
$title = '商品类别';
$this->layout()->currentItem = $title;
$this->headTitle($title);

$tableOptions = array(
    'cols' => array(
        array(
            'title' => '类别名称',
            'key' => 'title'
        )
    ),
    'getListDataUrl' => '/category/getCategoriesListData',
    'operatingCol' => array(
        'editUrl' => '/category/edit/',
        'deleteUrl' => '/category/delete/',
    )
)?>
<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/category/add"><i
				class="ace-icon glyphicon glyphicon-plus"></i>新增商品类别</a></small>
	</h1>
</div>
<div class="row">
	<div class="col-xs-12">
         <?=$this->flashMessenger()->render();?>
         <div class="row">
			<div class="col-xs-12">
				<?=$this->dataTable($tableOptions)?>
			</div>
		</div>
	</div>
</div>


