<?php
$title = '商品类别管理';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/main/category-list.js'));
?>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/category/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品类别</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
         <?=$this->flashMessenger()->render();?>
         <div class="row">
            <div class="col-xs-12">
                <table id="category-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                            <th>类别名称</th>
                            <th>类别类型</th>
                            <th>&nbsp;</th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


