<?php
echo $this->doctype();
?>

<html lang="en">
    <head>

		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
		<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php $this->headscript()->appendFile($this->basepath('js/jquery.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/bootstrap.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/bootstrap-wysiwyg.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/ace.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/ace-elements.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/ace-extra.min.js'))?>
        <?php $this->headscript()->appendFile($this->basepath('js/jquery.qrcode.min.js'))?>


		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/font-awesome.min.css" />

		<!-- page specific plugin styles -->

		<!-- text fonts -->
		<link rel="stylesheet" href="/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/css/ace.min.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="/css/ace-skins.min.css" />
		<link rel="stylesheet" href="/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="/css/admin-site/admin.css" />


		<?php echo $this->headscript();?>
		<?php echo $this->headLink() ?>
        <?php echo $this->headTitle('捷店')->setSeparator(' - ')->setAutoEscape(false) ?>

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->


		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/js/html5shiv.js"></script>
		<script src="/js/respond.min.js"></script>
		<![endif]-->
        <meta property="wb:webmaster" content="176d06dc51ce9a74" />
    </head>
    <body class="no-skin">
		<?=$this->partial('/layout/nav.phtml')?>
        <div class="main-container" id="main-container">
        	<script type="text/javascript">
        		try{ace.settings.check('main-container' , 'fixed')}catch(e){}
        	</script>

        	<?=$this->partial('/layout/sidebar.phtml', array('currentItem' => $currentItem))?>


        	<div class="main-content">
                <?=$this->partial('/layout/breadcrumbs.phtml')?>
                <div class="page-content">
                    <div class="page-content-area">
                        <?php echo $this->content; ?>
            		</div>
                </div>
        	</div>

            <?=$this->partial('/layout/footer.phtml')?>
            <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse display">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
        </div><!-- /.main-container -->

        <?php $this->inlinescript()->appendFile($this->basepath('js/wds/admin/core.js'))?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
