<?php
$this->inlinescript()->appendFile( $this->basePath('js/wds/admin/product.js') );

$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="col-md-6">
<?php
echo $this->formRow($form->get('code'));
echo $this->formRow($form->get('gender'));
echo $this->formRow($form->get('id_type'));
echo $this->formRow($form->get('address'));
?>
</div>
<div class="col-md-6">
<?php
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('dob'));
echo $this->formRow($form->get('id_code'));
echo $this->formRow($form->get('phone'));
?>
</div>
<?php





?>
<?php
echo $this->formActions($form->get('submit'));
echo $this->form()->closeTag();
?>





<div id="modal-form" class="modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger">请输入商品类别</h4>
			</div>
			<div class="modal-body">
			    <form action="/admin/product/category/addByAjax" id="category-form">
    				<div class="row">
    					<div class="col-xs-12">
    						<div class="form-group">
    							<label for="form-field-username">商品类别</label>
    							<div>
    								<input class="input-large" type="text" id="form-field-category" name="title" placeholder="商品类别" value="" />
    							</div>
    						</div>
    					</div>
    				</div>
				</form>
			</div>
			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					取消
				</button>

				<button class="btn btn-sm btn-primary btn-modal-form-submit" data-submit="category-form">
					<i class="ace-icon fa fa-check"></i>
					保存
				</button>
			</div>
		</div>
	</div>
</div><!-- PAGE CONTENT ENDS -->
