 <div class="row">
	<div class="col-xs-12">
	<form id="w0" class="form-horizontal" action="/Tellyes-GP-Training/backend/web/case/index" method="get" role="form">
	
		<div class=" container-search container-fluid">
			<div class="form-submit-group">
                <button type="submit" class="btn btn-primary btn-sm">查询</button>
            </div>
        
            
            
            <div class="row">
            	<div class="col-xs-6">
            		<div class="form-group field-medicalcasesearch-title">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">宝贝名称</label>
                        <div class="col-sm-6">
                        	<input type="text" id="medicalcasesearch-title" class="form-control" name="MedicalCaseSearch[title]">
                        	<div class="help-block help-block-error "></div>
                        </div>
                    </div>
            	</div>
            	<div class="col-xs-6">
            		<div class="form-group field-medicalcasesearch-title">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">宝贝名称</label>
                        <div class="col-sm-6">
                        	<input type="text" id="medicalcasesearch-title" class="form-control" name="MedicalCaseSearch[title]">
                        	<div class="help-block help-block-error "></div>
                        </div>
                    </div>
            	</div>
            </div>
		</div>
		</form>
	</div>
</div>