 <div class="row">
	<div class="col-xs-12">
	<form id="w0" class="form-horizontal" role="form">
	
		<div class=" container-search container-fluid">
			<div class="form-submit-group">
                <button type="button" id="search-submit" class="btn btn-primary btn-sm">查询</button>
            </div>
            
            
            <div class="row">
            	<div class="col-xs-6">
            		<div class="form-group ">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">宝贝名称</label>
                        <div class="col-sm-6">
                        	<input type="text" id="member-search-name" class="form-control" name="name">
                        	<div class="help-block help-block-error "></div>
                        </div>
                    </div>
            	</div>
            	<div class="col-xs-6">
            		<div class="form-group ">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">会员生日</label>
                        <div class="col-sm-6">
                        	<div class="input-group">
                        	<input type="text" class="form-control date-picker" data-date-format="mm-dd" name="dob" value="">
                        	<span class="input-group-addon"><i class="fa fa-calendar bigger-110"></i></span>
                        	<div class="help-block help-block-error "></div>
                        	</div>
                        </div>
                    </div>
            	</div>
        	</div>
        	 <div class="row">
            	<div class="col-xs-6">
            		<div class="form-group ">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">会员卡号</label>
                        <div class="col-sm-6">
                        	<input type="text" id="" class="form-control" name="code">
                        	<div class="help-block help-block-error "></div>
                        </div>
                    </div>
            	</div>
            	<div class="col-xs-6">
            		<div class="form-group ">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">电话</label>
                        <div class="col-sm-6">
                        	<input type="text" id="" class="form-control" name="phone">
                        	<div class="help-block help-block-error "></div>
                        </div>
                    </div>
            	</div>
            </div>
        	 <div class="row">
            	<div class="col-xs-6">
            		<div class="form-group ">
                        <label class="control-label col-sm-3" for="medicalcasesearch-title">状态</label>
                        <div class="col-sm-6">
							
							<label class="radio-inline">
                              <input type="radio"  value="1" name="status"> 正常
                            </label>
							
							<label class="radio-inline">
                              <input type="radio"  value="0" name="status"> 禁用
                            </label>
                        </div>
                    </div>
            	</div>
            	<div class="col-xs-6">
            	</div>
            </div>
		</div>
	</form>
	</div>
</div>