<?php
use Application\Model\Member\Member;
$title = '会员列表';
$this->layout()->currentItem = $title;
$this->headTitle($title);

$this->inlinescript()->appendFile($this->basePath('js/main/member/list.js'));

$tableOptions = array(
    'dataTableName' => 'member',
    'cols' => array(
        array(
            'title' => '会员卡号',
            'key' => 'code',
            'linkTarget' => 'editLink'
        ),
        array(
            'title' => '宝贝名称',
            'key' => 'name'
        ),
        array(
            'title' => '手机/电话',
            'key' => 'phone'
        ),
        array(
            'title' => '监护人名称',
            'key' => 'parent_name'
        ),
        array(
            'title' => '积分',
            'key' => 'point'
        ),
        array(
            'title' => '办卡日期',
            'key' => 'created_time'
        ),
        array(
            'title' => '会员生日',
            'key' => 'dob'
        ),
        array(
            'title' => '经办人',
            'key' => 'referral_staff_name'
        ),
        array(
            'title' => '状态',
            'key' => 'statusString'
        )
    ),
    'getListDataUrl' => '/member/getMemberListData',
    'operatingCol' => array(
        'editUrl' => '/member/profile/<{RowId}>',
        'deleteUrl' => array(
            'url' => '/member/delete/<{RowId}>',
            'type' => 'deleteUrl',
            'condition' => array(
                'status' => Member::MEMBER_STATUS_DISABLE
            )
        ),
        'disable' => array(
            'url' => '/member/disableMember/<{RowId}>',
            'type' => 'confirmModal',
            'label' => '禁用',
            'condition' => array(
                'status' => Member::MEMBER_STATUS_NORMAL
            )
        ),
        'enable' => array(
            'url' => '/member/enableMember/<{RowId}>',
            'type' => 'confirmModal',
            'label' => '启用',
            'condition' => array(
                'status' => Member::MEMBER_STATUS_DISABLE
            )
        )
    )
)?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/member/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增会员</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
            <?=$this->dataTable($tableOptions)?>
            </div>
        </div>
    </div>
</div>


<div id="modal-confirm" class="modal" tabindex="-1"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue" id="myModalLabel">确认</h4>
			</div>
			<div class="modal-body center">
				<div class="row">
					<div class="col-xs-12">
                        <div class="modal-title">是否对 <span id="item-name"></span> 执行<span id="item-operate"></span>操作？</div>
                        <form id="modal_confirm_form">
                        <input type="hidden" name="id">
                        </form>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					否
				</button>

				<button class="btn btn-sm btn-primary" id="btn-delete-submit">
					<i class="ace-icon fa fa-check"></i>
					是
				</button>
			</div>
		</div>
	</div>
</div>

