<?php
$title = '会员列表';
$this->layout()->currentItem = $title;
$this->headTitle($title);

$tableOptions = array(
    'cols' => array(
        array(
            'title' => '会员卡号',
            'key' => 'code',
            'linkTarget' => 'editLink'
        ),
        array(
            'title' => '宝贝名称',
            'key' => 'name'
        ),
        array(
            'title' => '手机/电话',
            'key' => 'phone'
        ),
        array(
            'title' => '监护人名称',
            'key' => 'parent_name'
        ),
        array(
            'title' => '积分',
            'key' => 'point'
        )
    ),
    'getListDataUrl' => '/member/getMemberListData',
    'operatingCol' => array(
        'editUrl' => '/member/edit/',
        'deleteUrl' => '/member/delete/',
    )
)?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/member/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增会员</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
            <?=$this->dataTable($tableOptions)?>
            </div>
        </div>
    </div>
</div>

