<?php
$title = '会员列表';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/main/member-list.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/member/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增会员</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <table id="data-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                    	  <th>会员卡号</th>
                            <th>宝贝名称</th>
                            <th>手机/电话</th>
                            <th>会员类别</th>
                            <th>卡内余额</th>
                            <th>积分</th>
                            <th>发卡人</th>
                            <th>发卡店</th>
                            <th>有效期</th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

