<?php
$title = '会员信息';
$this->layout()->currentItem = $title;
$this->headTitle($title);

$memberGoodsTableOptions = array(
    'cols' => array(
        array(
            'title' => '商品代码',
            'key' => 'goods_code'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title'
        ),
        array(
            'title' => '详情',
            'key' => 'detail'
        ),
        array(
            'title' => '备注',
            'key' => 'description'
        )
    ),
    'getListDataUrl' => '/member/getMemberGoodsListData',
    'operatingCol' => false
);
$memberActionTableOptions = array(
    'dataTableName' => 'memberAction',
    'cols' => array(
        array(
            'title' => '商品代码',
            'key' => 'goods_code'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title'
        ),
        array(
            'title' => '动作',
            'key' => 'action'
        ),
        array(
            'title' => '时间',
            'key' => 'create_time'
        )
    ),
    'getListDataUrl' => '/member/getMemberLogListData',
    'operatingCol' => false
)?>


<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
	<div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
			<div class="col-xs-12">
				<div class="profile-user-info profile-user-info-striped">
					<div class="profile-info-row">
						<div class="profile-info-name">姓名</div>

						<div class="profile-info-value"><?=$member->name?></div>
						<div class="profile-info-name">会员卡号</div>

						<div class="profile-info-value"><?=$member->code?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">性别</div>

						<div class="profile-info-value"><?=$member->gender?></div>
						<div class="profile-info-name">生日</div>

						<div class="profile-info-value"><?=$member->dob?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">监护人姓名</div>

						<div class="profile-info-value"><?=$member->parent_name?></div>
						<div class="profile-info-name">电话</div>

						<div class="profile-info-value"><?=$member->phone?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">办卡日期</div>

						<div class="profile-info-value"><?=$member->created_time?></div>
						<div class="profile-info-name">积分</div>

						<div class="profile-info-value"><?=$member->point?></div>
					</div>
				</div>
			</div>
		</div>
		<div class="hr dotted"></div>
		<div class="row">
			<div class="col-xs-12">
				<div class="tabbable">
					<ul class="nav nav-tabs padding-18">
						<li class="active"><a data-toggle="tab" href="#member-goods"> <i
								class="purple ace-icon fa fa-credit-card bigger-120"></i> 消费卡管理
						</a></li>

						<li><a data-toggle="tab" href="#history"> <i
								class="orange ace-icon fa fa-history bigger-120"></i> 卡消费明细
						</a></li>


					</ul>

					<div class="tab-content no-border padding-24">

						<div id="member-goods" class="tab-pane in active">
							<div class="row">
								<div class="col-xs-12">
									<a href="#modal-form" data-toggle="modal" role="button"
										class="btn btn-yellow btn-sm pull-right" id="buy-button"> <i
										class="ace-icon fa fa-plus"></i>续卡
									</a>

								</div>
							</div>
							<div class="space"></div>
							<div class="row">
								<div class="col-xs-12">
    						      <?=$this->dataTable($memberGoodsTableOptions)?>
                                </div>
							</div>
						</div>
						<div id="history" class="tab-pane"><?=$this->dataTable($memberActionTableOptions)?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="modal-form" class="modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger">Please fill the following form fields</h4>
			</div>

			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12">
						<div class="form-group">
							<label for="form-field-select-3">Location</label>

							<div>
								<select class="chosen-select"
									data-placeholder="Choose a Country...">
									<option value="">&nbsp;</option>
									<option value="AL">Alabama</option>
									<option value="AK">Alaska</option>
									<option value="AZ">Arizona</option>
									<option value="AR">Arkansas</option>
									<option value="CA">California</option>
									<option value="CO">Colorado</option>
									<option value="CT">Connecticut</option>
									<option value="DE">Delaware</option>
									<option value="FL">Florida</option>
									<option value="GA">Georgia</option>
									<option value="HI">Hawaii</option>
									<option value="ID">Idaho</option>
									<option value="IL">Illinois</option>
									<option value="IN">Indiana</option>
									<option value="IA">Iowa</option>
									<option value="KS">Kansas</option>
									<option value="KY">Kentucky</option>
									<option value="LA">Louisiana</option>
									<option value="ME">Maine</option>
									<option value="MD">Maryland</option>
									<option value="MA">Massachusetts</option>
									<option value="MI">Michigan</option>
									<option value="MN">Minnesota</option>
									<option value="MS">Mississippi</option>
									<option value="MO">Missouri</option>
									<option value="MT">Montana</option>
									<option value="NE">Nebraska</option>
									<option value="NV">Nevada</option>
									<option value="NH">New Hampshire</option>
									<option value="NJ">New Jersey</option>
									<option value="NM">New Mexico</option>
									<option value="NY">New York</option>
									<option value="NC">North Carolina</option>
									<option value="ND">North Dakota</option>
									<option value="OH">Ohio</option>
									<option value="OK">Oklahoma</option>
									<option value="OR">Oregon</option>
									<option value="PA">Pennsylvania</option>
									<option value="RI">Rhode Island</option>
									<option value="SC">South Carolina</option>
									<option value="SD">South Dakota</option>
									<option value="TN">Tennessee</option>
									<option value="TX">Texas</option>
									<option value="UT">Utah</option>
									<option value="VT">Vermont</option>
									<option value="VA">Virginia</option>
									<option value="WA">Washington</option>
									<option value="WV">West Virginia</option>
									<option value="WI">Wisconsin</option>
									<option value="WY">Wyoming</option>
								</select>
							</div>
						</div>

						<div class="space-4"></div>

						<div class="form-group">
							<label for="form-field-username">Username</label>

							<div>
								<input type="text" id="form-field-username"
									placeholder="Username" value="alexdoe" />
							</div>
						</div>

						<div class="space-4"></div>

						<div class="form-group">
							<label for="form-field-first">Name</label>

							<div>
								<input type="text" id="form-field-first"
									placeholder="First Name" value="Alex" /> <input type="text"
									id="form-field-last" placeholder="Last Name" value="Doe" />
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i> Cancel
				</button>

				<button class="btn btn-sm btn-primary">
					<i class="ace-icon fa fa-check"></i> Save
				</button>
			</div>
		</div>
	</div>
</div>
<!-- PAGE CONTENT ENDS -->
