<?php
$title = '会员信息';
$this->layout()->currentItem = $title;
$this->headTitle($title);


$this->headlink()->appendStylesheet($this->basePath('css/datepicker.css'));
$this->inlinescript()
    ->appendFile($this->basePath('js/chosen.jquery.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-datepicker.js'))
    ->appendFile($this->basePath('js/date-time/bootstrap-datepicker.zh.js'))
    ->appendFile($this->basePath('js/main/member/profile.js'));

$memberGoodsTableOptions = array(
    'dataTableName' => 'memberGoods',
    'cols' => array(
        array(
            'title' => '商品代码',
            'key' => 'goods_code'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title'
        ),
        array(
            'title' => '详情',
            'key' => 'detail',
            'orderable' => 'false'
        ),
        array(
            'title' => '备注',
            'key' => 'description',
            'orderable' => 'false'
        ),
        array(
            'title' => '购买时间',
            'key' => 'create_time'
        )
    ),
    'getListDataUrl' => '/member/getMemberGoodsListData',
    'getListDataParams' => array(
        'member_id' => $member->id
    ),
    'operatingCol' => false
);
$memberActionTableOptions = array(
    'dataTableName' => 'memberAction',
    'cols' => array(
        array(
            'title' => '商品代码',
            'key' => 'goods_code'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title'
        ),
        array(
            'title' => '动作',
            'key' => 'action'
        ),
        array(
            'title' => '次数',
            'key' => 'count'
        ),
        array(
            'title' => '时间',
            'key' => 'create_time'
        )
    ),
    'getListDataUrl' => '/member/getMemberLogListData',
    'getListDataParams' => array(
        'member_id' => $member->id
    ),
    'operatingCol' => false
)?>
<style>
<!--
.modal-dialog .input-group{  z-index: 1151 ; }
.chosen-container .chosen-drop{ z-index: 1152 !important; }
-->
</style>

<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
	<div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
			<div class="col-xs-10">
				<div class="profile-user-info profile-user-info-striped">
					<div class="profile-info-row">
						<div class="profile-info-name">姓名</div>

						<div class="profile-info-value"><?=$member->name?></div>
						<div class="profile-info-name">会员卡号</div>

						<div class="profile-info-value"><?=$member->code?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">性别</div>

						<div class="profile-info-value"><?=$member->gender?></div>
						<div class="profile-info-name">生日</div>

						<div class="profile-info-value"><?=$member->dob?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">监护人姓名</div>

						<div class="profile-info-value"><?=$member->parent_name?></div>
						<div class="profile-info-name">电话</div>

						<div class="profile-info-value"><?=$member->phone?></div>
					</div>

					<div class="profile-info-row">
						<div class="profile-info-name">办卡日期</div>

						<div class="profile-info-value"><?=$member->created_time?></div>
						<div class="profile-info-name">积分</div>

						<div class="profile-info-value"><?=$member->point?></div>
					</div>
				</div>
			</div>
			<div class="col-xs-2">
				<a href="/member/edit/<?=$member->id?>" data-toggle="modal" role="button"
					class="btn btn-info btn-block " id="buy-button"> <i
					class="ace-icon glyphicon glyphicon-pencil"></i>编辑
				</a> <a href="#modal-form" data-toggle="modal" role="button"
					class="btn btn-yellow btn-block " id="buy-button"> <i
					class="ace-icon fa fa-plus"></i>续卡
				</a>

			</div>
		</div>
		<div class="hr dotted"></div>
		<div class="row">
			<div class="col-xs-12">
				<div class="tabbable">
					<ul class="nav nav-tabs padding-18">
						<li class="active"><a data-toggle="tab" href="#member-goods"> <i
								class="purple ace-icon fa fa-credit-card bigger-120"></i> 消费卡管理
						</a></li>

						<li><a data-toggle="tab" href="#history"> <i
								class="orange ace-icon fa fa-history bigger-120"></i> 卡消费明细
						</a></li>


					</ul>

					<div class="tab-content no-border padding-24">

						<div id="member-goods" class="tab-pane in active">
					       <?=$this->dataTable($memberGoodsTableOptions)?>
						</div>
						<div id="history" class="tab-pane"><?=$this->dataTable($memberActionTableOptions)?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="modal-form" class="modal" tabindex="-1">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue bigger">续卡</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12">
						<form action="" method="POST" name="buy_goods_form"
							class="form-horizontal" role="form" id="buy_goods_form">
							<input type="hidden" name="member_id" value="<?=$member->id?>">
							<div class="form-group ">
								<label for="form-field-select-3"
									class="col-sm-3 control-label no-padding-right">商品卡</label>
								<div class="col-sm-7">
									<select class="chosen-select form-control goods-chosen-select"
										data-placeholder="请选择商品" name="goods_id">
										<option value="" data-goods-type=""></option>
										<?php foreach ($goods as $goodsItem):?>
										<option value="<?=$goodsItem['value']?>"
											data-goods-type="<?=$goodsItem['attributes']['data-goods-type']?>"
											data-goods-count="<?=$goodsItem['attributes']['data-goods-count']?>"><?=$goodsItem['label']?></option>
										<?php endforeach;?>
									</select>
								</div>
							</div>

							<div class="form-group time-card-only">
								<label class="col-sm-3 control-label no-padding-right"
									for="form-field-1">是否开卡</label>
								<div class="col-sm-7" style="padding-top: 7px;">
									<label> <input id="checkbox-start" name="checkbox-start"
										type="checkbox" class="ace" checked="checked" /> <span
										class="lbl">现在开卡</span>
									</label>
								</div>
							</div>

							<div class="form-group time-card-only">
								<label class="col-sm-3 control-label no-padding-right"
									for="form-field-1">开始时间</label>
								<div class="col-sm-7">
									<div class="input-group">
										<input type="text" placeholder="开始时间"
											name="start_date" class="form-control date-picker" data-date-format="yyyy-mm-dd" ><span
											class="input-group-addon"> <i
											class="fa fa-calendar bigger-110"></i>
										</span>
									</div>
								</div>
							</div>


							<div class="form-group time-card-only">
								<label class="col-sm-3 control-label no-padding-right"
									for="form-field-1">结束时间</label>
								<div class="col-sm-7">
									<div class="input-group">
										<input type="text" placeholder="结束时间"
											name="end_date" class="form-control date-picker" data-date-format="yyyy-mm-dd" ><span
											class="input-group-addon"> <i
											class="fa fa-calendar bigger-110"></i>
										</span>
									</div>
								</div>
							</div>

							<div class="form-group count-card-only">
								<label class="col-sm-3 control-label no-padding-right"
									for="form-field-1">次数</label>
								<div class="col-sm-7">
									<input type="text" id="form-count" placeholder="次数"
										name="count" class="form-control" value="0" />
								</div>
							</div>

							<div class="form-group">
								<label class="col-sm-3 control-label no-padding-right"
									for="form-field-1">备注</label>
								<div class="col-sm-7">
									<textarea rows="" cols="" class="form-control" placeholder="备注"
										name="description"></textarea>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i> 取消
				</button>

				<button id="btn-submit-buy-modal" class="btn btn-sm btn-primary">
					<i class="ace-icon fa fa-check"></i> 保存
				</button>
			</div>
		</div>
	</div>
</div>
<!-- PAGE CONTENT ENDS -->

