<?php

$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('role', 'form');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="col-md-6">
<?php
echo $this->formRow($form->get('login_name'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('address'));
echo $this->formRow($form->get('role'));
?>
</div>
<div class="col-md-6">
<?php
echo $this->formRow($form->get('staff_name'));
echo $this->formRow($form->get('confirm_password'));
echo $this->formRow($form->get('phone'));
echo $this->formRow($form->get('fake_log_discount'));
?>
</div>
<div class="form-group">
    <div class="col-sm-offset-1 col-sm-12">
        <?=$this->formActions($form->get('submit'));?>
    </div>
</div>
<?php
// echo $this->formActions( $form->get('cancel'), $form->get('submit'));
echo $this->form()->closeTag();
?>

