<?php
$title = '店铺员工';
$this->layout()->currentItem = $title;
$this->headTitle($title);

$tableOptions = array(
    'cols' => array(
        array(
            'title' => '员工姓名',
            'key' => 'staff_name'
        ),
        array(
            'title' => '登陆名',
            'key' => 'login_name'
        ),
        array(
            'title' => '角色',
            'key' => 'role'
        ),
    ),
    'getListDataUrl' => '/staff/getStaffListData',
    'operatingCol' => array(
        'editUrl' => '/staff/edit/<{RowId}>',
        'deleteUrl' => '/staff/delete/<{RowId}>',
    )
)?>
<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/staff/add"><i
				class="ace-icon glyphicon glyphicon-plus"></i>新增员工</a></small>
	</h1>
</div>
<div class="row">
	<div class="col-xs-12">
         <?=$this->flashMessenger()->render();?>
         <div class="row">
			<div class="col-xs-12">
				<?=$this->dataTable($tableOptions)?>
			</div>
		</div>
	</div>
</div>


