<?php
$title = '订单';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/wds/admin/order-list.js'));
?>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/admin/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <table id="product-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                            <th>&nbsp;</th>
                            <th>商品名称</th>
                            <td>订货数量</th>
                            <th>&nbsp;</th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


