<?php
$this->layout()->headerTitle = '首页';
?>
<ul data-role="listview" data-inset="true" class="ui-nodisc-icon ui-alt-icon">
	<li data-role="list-divider">推荐商品</li>
	<?php foreach ($products as $product):?>
	<li>
		<a href="/p/<?=$product->id?>" data-transition="fade">
			<img src="<?=$product->product_thumbnail?>">
			<h2><?=$product->title?></h2>
			<p>¥ <?=$product->price?> / <?=$product->unit?></p>
		</a>
	</li>
	<?php endforeach;?>
</ul>

<ul data-role="listview" data-inset="true" class="ui-nodisc-icon ui-alt-icon">
	<?php foreach ($categories as $category): ?>
	<li><a href="/g/<?=$category->id?>" data-transition="fade"><?= $category->title?></a></li>
	<?php endforeach;?>
</ul>
