<?php
$title = '快速消费';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()
    ->appendFile($this->basePath('js/chosen.jquery.js'))
    ->appendFile( $this->basePath('js/main/sale/sale.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>

        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="row">
                    <div class="col-sm-9">
                        <form class="form-horizontal" role="form">
                        	<!-- #section:elements.form -->
                        	<div class="form-group">
                        		<label class="col-sm-2 control-label no-padding-right" for="form-field-1">会员卡号</label>

                        		<div class="col-sm-10">
                        			<input type="text" id="member-code" placeholder="会员卡号" class="col-sm-10">
                        		</div>
                        	</div>
                        	<div class="form-group">
                        		<label class="col-sm-2 control-label no-padding-right" for="form-field-1">商品条码</label>

                        		<div class="col-sm-10">
                                    <select class="goods-chosen-select col-sm-10"
										data-placeholder="请选择商品" name="goods_id">
										<option value="" data-goods-type=""></option>
										<?php foreach ($goods as $goodsItem):?>
										<option value="<?=$goodsItem['value']?>"
											data-goods-type="<?=$goodsItem['attributes']['data-goods-type']?>"><?=$goodsItem['label']?></option>
										<?php endforeach;?>
									</select>
                        		</div>
                        	</div>
                        </form>
                    </div>
                    <div class="col-sm-3">
                        <button class="btn btn-app btn-yellow btn-sm" id="buy-button">
							<i class="ace-icon fa fa-shopping-cart bigger-160"></i>
							购买
						</button>
                    </div>
                </div>
    			<div class="well">
    				<h4 class="green smaller lighter">会员信息</h4>
    				<ul class="list-inline member-info-list"></ul>
    			</div>
                <div>
            		<table class="table table-striped table-bordered" id="goods-tbl" data-rownum="0" data-total="0">
            			<thead>
            				<tr>
            					<th class="center">#</th>
            					<th>商品</th>
            					<th class="hidden-xs">说明</th>
            					<th class="hidden-480">折扣</th>
            					<th>单价</th>
            					<th></th>
            				</tr>
            			</thead>

            			<tbody>
            			</tbody>
            		</table>
                </div>
                <div class="hr hr8 hr-double hr-dotted"></div>

				<div class="row">
					<div class="col-sm-5 pull-right">
						<h4 class="pull-right">
							合计:
							<span class="red">￥<span id="total-price">0.00</span></span>
						</h4>
					</div>
					<div class="col-sm-7 pull-left"></div>
				</div>
            </div>
        </div>
    </div>
</div>
<form id="buyGoodsForm" method="post">
<input type="hidden" id="member_code" name="member_code">
<input type="hidden" id="goods_code_arr" name="goods_code_arr">
</form>
