<?php
$title = '快速消费';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/main/member-list.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <form class="form-horizontal" role="form">
        	<!-- #section:elements.form -->
        	<div class="form-group">
        		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">会员卡号</label>

        		<div class="col-sm-9">
        			<input type="text" id="form-field-1" placeholder="会员卡号" class="col-xs-10 col-sm-5">
        		</div>
        	</div>
        	<div class="form-group">
        		<label class="col-sm-3 control-label no-padding-right" for="form-field-1">商品条码</label>

        		<div class="col-sm-9">
        			<input type="text" id="form-field-1" placeholder="商品条码" class="col-xs-10 col-sm-5">
        		</div>
        	</div>
        	<div class="clearfix form-actions">
				<div class="col-md-offset-3 col-md-9">
					<button class="btn btn-info" type="button">
						<i class="ace-icon fa fa-check bigger-110"></i>
						支付
					</button>
				</div>
			</div>
        </form>
    </div>
</div>

