<?php
$title = '快速消费';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/main/sale.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>

        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="row">
                    <div class="col-sm-9">
                        <form class="form-horizontal" role="form">
                        	<!-- #section:elements.form -->
                        	<div class="form-group">
                        		<label class="col-sm-2 control-label no-padding-right" for="form-field-1">会员卡号</label>

                        		<div class="col-sm-10">
                        			<input type="text" id="form-field-1" placeholder="会员卡号" class="col-sm-10">
                        		</div>
                        	</div>
                        	<div class="form-group">
                        		<label class="col-sm-2 control-label no-padding-right" for="form-field-1">商品条码</label>

                        		<div class="col-sm-10">
                        			<input type="text" id="form-field-1" placeholder="商品条码" class="col-sm-10">
                        		</div>
                        	</div>
                        </form>
                    </div>
                    <div class="col-sm-3">
                        <a href="#" class="btn btn-app btn-yellow btn-sm">
							<i class="ace-icon fa fa-shopping-cart bigger-160"></i>
							购买
						</a>
                    </div>
                </div>
    			<div class="well">
    				<h4 class="green smaller lighter">会员信息</h4>
    				<ul class="list-inline member-info-list">
    					<li>
    						<i class="ace-icon fa fa-caret-right blue"></i>Street, City
    					</li>
    					<li>
    						<i class="ace-icon fa fa-caret-right blue"></i>Zip Code
    					</li>
    					<li>
    						<i class="ace-icon fa fa-caret-right blue"></i>State, Country
    					</li>

    				</ul>
    			</div>
                <div>
            		<table class="table table-striped table-bordered">
            			<thead>
            				<tr>
            					<th class="center">#</th>
            					<th>商品</th>
            					<th class="hidden-xs">说明</th>
            					<th class="hidden-480">折扣</th>
            					<th>单价</th>
            					<th></th>
            				</tr>
            			</thead>

            			<tbody>
            				<tr>
            					<td class="center">1</td>

            					<td>
            						<a href="#">google.com</a>
            					</td>
            					<td class="hidden-xs">
            						1 year domain registration
            					</td>
            					<td class="hidden-480"> --- </td>
            					<td>$10</td>
            					<td>$10</td>
            				</tr>


            			</tbody>
            		</table>
                </div>
            </div>
        </div>
    </div>
</div>

