<?php
$title = '会员扣次';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/main/sale/use.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>

        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-horizontal" role="form">
                        	<!-- #section:elements.form -->
                        	<div class="form-group">
                        		<label class="col-sm-2 control-label no-padding-right" for="form-field-1">会员卡号</label>

                        		<div class="col-sm-10">
                        			<input type="text" id="member-code" placeholder="会员卡号" class="col-sm-10">
                        		</div>
                        	</div>
                        </form>
                    </div>

                </div>
    			<div class="well">
    				<h4 class="green smaller lighter">会员信息</h4>
    				<ul class="list-inline member-info-list"></ul>
    			</div>
                <div>
            		<table class="table table-striped table-bordered" id="goods-tbl" data-rownum="0" data-total="0">
            			<thead>
            				<tr>
            					<th class="center">#</th>
            					<th>商品名称</th>
            					<th>说明</th>
            					<th></th>
            				</tr>
            			</thead>
            			<tbody>
            			</tbody>
            		</table>
                </div>

            </div>
        </div>
    </div>
</div>
<form id="useGoodsForm" method="post">
<input type="hidden" id="showpopup" name="showpopup" value="<?=$ticketUrl?>">
<input type="hidden" id="member_goods_code" name="member_goods_code">
</form>

<div id="modal-confirm" class="modal" tabindex="-1"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="blue" id="myModalLabel">确认</h4>
			</div>

			<div class="modal-body">
				<div class="row">
					<div class="col-xs-12">
					</div>
				</div>
			</div>

			<div class="modal-footer">
				<button class="btn btn-sm" data-dismiss="modal">
					<i class="ace-icon fa fa-times"></i>
					否
				</button>

				<button class="btn btn-sm btn-primary" id="btn-use-submit">
					<i class="ace-icon fa fa-check"></i>
					是
				</button>
			</div>
		</div>
	</div>
</div><!-- PAGE CONTENT ENDS -->