<?php
$title = '首页';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/wds/admin/category-list.js'));
?>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>


