<?php
$title = '童梦园 - 天津未来广场店';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()
    ->appendFile($this->basePath('js/flot/jquery.flot.js'))
    ->appendFile($this->basePath('js/main/dashboard.js'));

?>
<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="row">
			<div class="col-xs-12"></div>
		</div>
		<div class="row">
			<div class="col-xs-12">

				<div class="widget-box transparent">
					<div class="widget-header widget-header-flat">
						<h4 class="widget-title lighter">
							<i class="ace-icon fa fa-signal"></i> 本日数据
						</h4>
					</div>

					<div class="widget-body">
						<div class="widget-main padding-4">
							<div class="infobox infobox-green">
								<div class="infobox-icon">
									<i class="ace-icon fa fa-user"></i>
								</div>

								<div class="infobox-data">
									<span class="infobox-data-number"><?=$today->member_count?></span>
									<div class="infobox-content">会员光临</div>
								</div>

								<!-- #section:pages/dashboard.infobox.stat -->
<!-- 								<div class="stat stat-success">8%</div> -->

								<!-- /section:pages/dashboard.infobox.stat -->
							</div>

							<div class="infobox infobox-purple">
								<div class="infobox-icon">
									<i class="ace-icon fa fa-shopping-cart"></i>
								</div>

								<div class="infobox-data">
									<span class="infobox-data-number"><?=$today->sale_count?></span>
									<div class="infobox-content">商品销售</div>
								</div>

<!-- 								<div class="badge badge-success"> -->
<!-- 									+32% <i class="ace-icon fa fa-arrow-up"></i> -->
<!-- 								</div> -->
							</div>
						</div>
						<!-- /.widget-main -->
					</div>
					<!-- /.widget-body -->
				</div>
				<!-- /.widget-box -->
			</div>

			<div class="vspace-12-sm"></div>


			<!-- /.col -->
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="widget-box transparent">
					<div class="widget-header widget-header-flat">
						<h4 class="widget-title lighter">
							<i class="ace-icon fa fa-signal"></i> 最近30天趋势
						</h4>

<!-- 						<div class="widget-toolbar"> -->
<!-- 							<a href="#" data-action="collapse"> <i -->
<!-- 								class="ace-icon fa fa-chevron-up"></i> -->
<!-- 							</a> -->
<!-- 						</div> -->
					</div>

					<div class="widget-body">
						<div class="widget-main padding-4">
							<div id="sales-charts"></div>
						</div>
						<!-- /.widget-main -->
					</div>
					<!-- /.widget-body -->
				</div>
				<!-- /.widget-box -->
			</div>
		</div>
	</div>
</div>
<script>
<!--
var dashboard_last30_data = <?=$last30?>;
-->
</script>