<?php
echo $this->doctype();
?>

<html lang="en">
    <?php include_once __DIR__ . '/partials/head.phtml';?>
    <body class="no-skin">
    <?php include_once __DIR__ . '/partials/nav.phtml';?>
        <div class="main-container" id="main-container">
        	<script type="text/javascript">
        		try{ace.settings.check('main-container' , 'fixed')}catch(e){}
        	</script>


            <?php include_once __DIR__ . '/partials/sidebar.phtml';?>

        	<div class="main-content">
        	 <?php include_once __DIR__ . '/partials/breadcrumbs.phtml';?>
                <div class="page-content">
                    <div class="page-content-area">
                        <?php echo $this->content; ?>
            		</div>
                </div>
        	</div>

            <?php include_once __DIR__ . '/partials/footer.phtml';?>
        </div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?=$this->basepath('js/jquery.js')?>'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='<?=$this->basepath('js/jquery1x.js')?>'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?=$this->basepath('js/jquery.mobile.custom.js')?>'>"+"<"+"/script>");
		</script>
		<script src="<?=$this->basepath('js/bootstrap.js')?>"></script>
		<script src="<?=$this->basepath('js/jquery-ui.js')?>"></script>

		<!-- ace scripts -->
		<script src="<?=$this->basepath('js/ace/elements.scroller.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.colorpicker.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.fileinput.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.typeahead.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.wysiwyg.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.spinner.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.treeview.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.wizard.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/elements.aside.js')?>"></script>
		<script src="<?=$this->basepath('js/ace.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.ajax-content.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.touch-drag.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.sidebar.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.sidebar-scroll-1.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.submenu-hover.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.widget-box.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.settings.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.settings-rtl.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.settings-skin.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.widget-on-reload.js')?>"></script>
		<script src="<?=$this->basepath('js/ace/ace.searchbox-autocomplete.js')?>"></script>


		<!-- inline scripts related to this page -->

        <?php echo $this->inlineScript() ?>
        <?php include_once __DIR__ . '/partials/analytics.phtml';?>

    </body>
</html>
