<?php
echo $this->doctype();
?>

<html lang="en">
    <?php include_once __DIR__ . '/partials/head.phtml';?>
    <body class="no-skin">
    <?php include_once __DIR__ . '/partials/nav.phtml';?>
        <div class="main-container" id="main-container">
        	<script type="text/javascript">
        		try{ace.settings.check('main-container' , 'fixed')}catch(e){}
        	</script>


            <?php include_once __DIR__ . '/partials/sidebar.phtml';?>

        	<div class="main-content">
        	 <?php include_once __DIR__ . '/partials/breadcrumbs.phtml';?>
                <div class="page-content">
                    <div class="page-content-area">
                        <?php echo $this->content; ?>
            		</div>
                </div>
        	</div>

            <?php include_once __DIR__ . '/partials/footer.phtml';?>
        </div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script type="text/javascript">
			window.jQuery || document.write("<script src='<?=$this->basepath('js/jquery.js')?>'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='<?=$this->basepath('js/jquery1x.js')?>'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='<?=$this->basepath('js/jquery.mobile.custom.js')?>'>"+"<"+"/script>");
		</script>
		<script src="<?=$this->basepath('js/bootstrap.js')?>"></script>
		<script src="<?=$this->basepath('js/jquery-ui.js')?>"></script>

		<!-- ace scripts -->
		<script src="<?=$this->basepath('js/ace.js')?>"></script>
		<script src="<?=$this->basepath('js/ace-elements.js')?>"></script>

		<!-- inline scripts related to this page -->

        <?php echo $this->inlineScript() ?>
        <?php include_once __DIR__ . '/partials/analytics.phtml';?>

    </body>
</html>
