<div class="footer">
	<div class="footer-inner">
		<!-- #section:basics/footer -->
		<div class="footer-content">
			<span class="bigger-120">
				<span class="blue bolder">童梦园儿童乐园</span>
				© 2014-2015
			</span>
            <a href="http://www.miitbeian.gov.cn/">津ICP备14005532号</a>
			&nbsp; &nbsp;
<!-- 			<span class="action-buttons"> -->
<!-- 				<a href="#"> -->
<!-- 					<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i> -->
<!-- 				</a> -->

<!-- 				<a href="#"> -->
<!-- 					<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i> -->
<!-- 				</a> -->

<!-- 				<a href="#"> -->
<!-- 					<i class="ace-icon fa fa-rss-square orange bigger-150"></i> -->
<!-- 				</a> -->
<!-- 			</span> -->
		</div>

		<!-- /section:basics/footer -->
	</div>
</div>
<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse display">
	<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>