    <head>
        <meta charset="utf-8" />
		<meta name="description" content="" />
		<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>




		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/css/bootstrap.css" />
		<link rel="stylesheet" href="/css/font-awesome.css" />
		<link rel="stylesheet" href="/css/jquery-ui.css" />

		<!-- page specific plugin styles -->

		<!-- text fonts -->
		<link rel="stylesheet" href="/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/css/ace.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/css/ace-part2.css" />
		<![endif]-->
		<link rel="stylesheet" href="/css/ace-skins.css" />
		<link rel="stylesheet" href="/css/ace-rtl.css" />
		<link rel="stylesheet" href="/css/admin-site/admin.css" />


		<?php echo $this->headscript();?>
		<?php echo $this->headLink() ?>
        <?php echo $this->headTitle('童梦园儿童乐园')->setSeparator(' - ')->setAutoEscape(false) ?>

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->




		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		 <script src="/js/html5shiv.js"></script>
		<script src="/js/respond.min.js"></script>
		<![endif]-->
    </head>