<?php use SamFramework\Core\App;?>
<div class="navbar navbar-default" id="navbar">
	<script type="text/javascript">
		try{ace.settings.check('navbar' , 'fixed')}catch(e){}
	</script>

	<div class="navbar-container" id="navbar-container">

		<!-- #section:basics/sidebar.mobile.toggle -->
		<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
			<span class="sr-only">Toggle sidebar</span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>
		</button>

		<!-- /section:basics/sidebar.mobile.toggle -->
		<div class="navbar-header pull-left">
			<!-- #section:basics/navbar.layout.brand -->
			<a href="#" class="navbar-brand">
				<small>
					<i class="fa fa-leaf"></i>
					童梦园儿童乐园
				</small>
			</a>

			<!-- /section:basics/navbar.layout.brand -->

			<!-- #section:basics/navbar.toggle -->

			<!-- /section:basics/navbar.toggle -->
		</div>
		<!-- /.navbar-header -->

		<div class="navbar-buttons navbar-header pull-right" role="navigation">
			<ul class="nav ace-nav">

			<?php if (App::isGuest()) :?>
                <li class="light-blue ">
                    <a href="/account/login" >登陆 </a>
                </li>
            <?php else :?>
				<li class="light-blue">
					<a data-toggle="dropdown" href="#" class="dropdown-toggle">
    				    <span class="user-info"> <small>欢迎</small><?=App::getUser()->staff_name?> </span> <i class="ace-icon fa fa-caret-down"></i>
    				</a>
    				<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
     					<li>
     					  <a href="#"> <i class="ace-icon fa fa-cog"></i> Settings</a>
     					</li>
    					<li>
    					   <a href="#"> <i class="ace-icon fa fa-user"></i> Profile</a>
    					</li>
    					<li class="divider"></li>
    					<li>
    					<a href="/account/logout"> <i class="ace-icon fa fa-power-off"></i> Logout</a>
    					</li>
    				</ul>
				</li>
		      <?php endif;?>
			</ul>
			<!-- /.ace-nav -->
		</div>
		<!-- /.navbar-header -->
	</div>
	<!-- /.container -->
</div>