<?php use SamFramework\Core\App;?>
<div class="navbar navbar-default" id="navbar">
	<script type="text/javascript">
		try{ace.settings.check('navbar' , 'fixed')}catch(e){}
	</script>

	<div class="navbar-container" id="navbar-container">

		<!-- #section:basics/sidebar.mobile.toggle -->
		<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler">
			<span class="sr-only">Toggle sidebar</span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>

			<span class="icon-bar"></span>
		</button>

		<!-- /section:basics/sidebar.mobile.toggle -->
		<div class="navbar-header pull-left">
			<!-- #section:basics/navbar.layout.brand -->
			<a href="#" class="navbar-brand">
				<small>
					<i class="fa fa-leaf"></i>
					童梦园儿童乐园
				</small>
			</a>

			<!-- /section:basics/navbar.layout.brand -->

			<!-- #section:basics/navbar.toggle -->

			<!-- /section:basics/navbar.toggle -->
		</div>
		<!-- /.navbar-header -->

		<div class="navbar-header pull-right">
			<ul class="nav ace-nav">

			<?php if (App::isGuest()) :?>
                <li class="light-blue hidden-480">
                    <a href="/account/login" >登陆 </a>
                </li>
            <?php else :?>
				<li class="light-blue hidden-480">
    				<a data-toggle="dropdown" href="#" class="dropdown-toggle">
    				    <span class="user-info"> <small>Welcome,</small> Jason </span> <i class="icon-caret-down"></i>
    				</a>
    				<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
    <!-- 					<li> -->
    <!-- 					  <a href="#"> <i class="icon-cog"></i> Settings</a> -->
    <!-- 					</li> -->
    					<li>
    					  <a href="#"> <i class="icon-user"></i> Profile</a>
    					</li>
    					<li class="divider"></li>
    					<li>
    					<a href="/admin/account/logout"> <i class="icon-off"></i> Logout</a>
    					</li>
    				</ul>
				</li>
		      <?php endif;?>
			</ul>
			<!-- /.ace-nav -->
		</div>
		<!-- /.navbar-header -->
	</div>
	<!-- /.container -->
</div>