<?php
$menus = array(
    '首页' => array(
        'title' => '首页',
        'url' => '/dashboard'
    ),
    '会员管理' => array(
        'title' => '会员管理',
        'submenu' => array(
            array(
                'title' => '会员列表',
                'icon' => 'fa fa-tachometer',
                'url' => '/member/list'
            ),
            array(
                'title' => '新增会员',
                'icon' => 'fa fa-tachometer',
                'url' => '/member/add'
            ),
        )
    ),
    '商品管理' => array(
        'title' => '商品管理',
        'submenu' => array(
            array(
                'title' => '商品列表',
                'icon' => 'fa fa-tachometer',
                'url' => '/goods'
            ),
            array(
                'title' => '商品类别列表',
                'icon' => 'fa fa-tachometer',
                'url' => '/category'
            ),
        )
    ),
    '会员消费' => array(
        'title' => '会员消费',
        'url' => '/product/order'
    )
);

?>
<div class="sidebar responsive" id="sidebar">
    <script type="text/javascript">
        try {
            ace.settings.check('sidebar', 'fixed')
        } catch(e) {}
    </script>

	<div class="sidebar-shortcuts" id="sidebar-shortcuts">
		<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
			<button class="btn btn-success">
				<i class="ace-icon fa fa-signal"></i>
			</button>

			<button class="btn btn-info">
				<i class="ace-icon fa fa-pencil"></i>
			</button>

			<!-- #section:basics/sidebar.layout.shortcuts -->
			<button class="btn btn-warning">
				<i class="ace-icon fa fa-users"></i>
			</button>

			<button class="btn btn-danger">
				<i class="ace-icon fa fa-cogs"></i>
			</button>

			<!-- /section:basics/sidebar.layout.shortcuts -->
		</div>

		<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
			<span class="btn btn-success"></span>

			<span class="btn btn-info"></span>

			<span class="btn btn-warning"></span>

			<span class="btn btn-danger"></span>
		</div>
	</div><!-- /.sidebar-shortcuts -->

    <ul class="nav nav-list">
    <?=$this->sidebar($menus,$currentItem); ?>
    </ul>
    <!-- /.nav-list -->

	<!-- #section:basics/sidebar.layout.minimize -->
	<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
		<i class="ace-icon fa fa-angle-double-left" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
	</div>

	<!-- /section:basics/sidebar.layout.minimize -->
	<script type="text/javascript">
		try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
	</script>
</div>
<!-- End .sidebar -->