<!-- <div data-role="footer" data-position="fixed"> -->
<!--     <div data-role="navbar"> -->
<!--     	<ul> -->
<!--     		<li><a href="#" data-rel="back" class="ui-btn ui-icon-back ui-btn-icon-left">Back</a></li> -->
<!--     		<li><a href="/" data-transition="fade" class="ui-btn ui-icon-home ui-btn-icon-left">主页</a></li> -->
<!--     		<li><a href="#" class="ui-btn-active ui-state-persist">类别</a></li> -->
<!--     		<li><a href="#">其他</a></li> -->
<!--     	</ul> -->
<!--     </div> -->
<!--     </div> --><!-- /footer -->

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://182.92.180.124/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="http://182.92.180.124/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->