<?php
$title = '商品管理';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/wds/admin/product-list.js'));
?>
<style>
<!--
.qrcode-in-model{
	width: 130px;
	margin: auto;
}

-->
</style>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/admin/product/product/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <table id="product-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                            <th>&nbsp;</th>
                            <th>商品名称</th>
                            <th>&nbsp;</th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal" id="qrcodeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog  modal-sm">
    <div class="modal-content">
      <div class="modal-body">
        打开微信“扫一扫”，打开网页后点击屏幕右上角分享按钮
        <div class='qrcode-in-model'></div>
      </div>
    </div>
  </div>
</div>
