<?php
$title = '商品列表';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$tableOptions = array(
    'cols' => array(
        array(
            'title' => '商品代码',
            'key' => 'code'
        ),
        array(
            'title' => '商品名称',
            'key' => 'title'
        ),
        array(
            'title' => '类型',
            'key' => 'type'
        ),
        array(
            'title' => '类别',
            'key' => 'category_name'
        ),
        array(
            'title' => '价格',
            'key' => 'priceString'
        ),
        array(
            'title' => '说明',
            'key' => 'desc'
        )
    ),
    'getListDataUrl' => '/goods/getGoodsListData',
    'operatingCol' => array(
        'editUrl' => '/goods/edit/<{RowId}>',
        'deleteUrl' => '/goods/delete/<{RowId}>'
    )
)?>
<style>
<!--
.qrcode-in-model {
	width: 130px;
	margin: auto;
}
-->
</style>
<div class="page-header">
	<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/goods/add"><i
				class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
	</h1>
</div>
<div class="row">
	<div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
			<div class="col-xs-12">
            <?=$this->dataTable($tableOptions)?>
            </div>
		</div>
	</div>
</div>


