<?php
$title = '商品管理';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/main/product-list.js'));
?>
<style>
<!--
.qrcode-in-model{
	width: 130px;
	margin: auto;
}

-->
</style>
<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
    <small><a href="/goods/add"><i class="ace-icon glyphicon glyphicon-plus"></i>新增商品</a></small>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <table id="product-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                            <th>商品名称</th>
                            <th>类型</th>
                            <th>类别</th>
                            <th>价格</th>
                            <th>说明</th>
                            <th>&nbsp;</th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>


