<?php
$title = '店铺流水';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$tableOptions = array(
    'cols' => array(
        array(
            'title' => '会员卡号',
            'key' => 'member_code',
            'linkTarget' => '/member/edit/',
            'linkDataCol' => 'member_id'
        ),
        array(
            'title' => '会员名称',
            'key' => 'member_name',
            'linkTarget' => '/member/edit/',
            'linkDataCol' => 'member_id'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title',
            'linkTarget' => '/goods/edit/',
            'linkDataCol' => 'goods_id'
        ),
        array(
            'title' => '单价',
            'key' => 'price'
        ),
        array(
            'title' => '数量',
            'key' => 'quantity'
        ),
        array(
            'title' => '小计',
            'key' => 'total_price'
        ),
        array(
            'title' => '发生日期',
            'key' => 'create_time'
        ),
        array(
            'title' => '操作人',
            'key' => 'staff_name',
            'linkTarget' => '/staff/edit/',
            'linkDataCol' => 'user_id'
        )
    ),
    'getListDataUrl' => '/store/getSellLogListData',
    'operatingCol' => false
)?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <?=$this->dataTable($tableOptions)?>
            </div>
        </div>
    </div>
</div>

