<?php
$title = '店铺流水';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$this->inlinescript()->appendFile( $this->basePath('js/jquery.dataTables.min.js'))
                     ->appendFile( $this->basePath('js/jquery.dataTables.bootstrap.js'))
                     ->appendFile( $this->basePath('js/main/store/sell-log-list.js'));
?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <table id="data-table" class="table table-striped table-bordered table-hover">
                    <thead>
                    	<tr>
                            <th>会员卡号</th>
                            <th>会员名称</th>
                            <th>商品名称</th>
                            <th>单价</th>
                            <th>数量</th>
                            <th>小计</th>
                            <th>操作人</th>
                            <th></th>
                    	</tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

