<?php
$title = '店铺流水';
$this->layout()->currentItem = $title;
$this->headTitle($title);
$tableOptions = array(
    'cols' => array(
        array(
            'title' => '会员卡号',
            'key' => 'member_code',
//             'type' => 'editLink'
        ),
        array(
            'title' => '会员名称',
            'key' => 'member_name'
        ),
        array(
            'title' => '商品名称',
            'key' => 'goods_title'
        ),
        array(
            'title' => '单价',
            'key' => 'price'
        ),
        array(
            'title' => '数量',
            'key' => 'quantity'
        ),
        array(
            'title' => '小计',
            'key' => 'total_price'
        ),
        array(
            'title' => '操作人',
            'key' => 'user_name'
        )
    ),
    'getListDataUrl' => '/store/getSellLogListData',
    'operatingCol' => false
)?>

<div class="page-header">
<h1>
    <?= $this->escapeHtml($title); ?>
</h1>
</div>
<div class="row">
    <div class="col-xs-12">
        <?=$this->flashMessenger()->render();?>
        <div class="row">
            <div class="col-xs-12">
                <?=$this->dataTable($tableOptions)?>
            </div>
        </div>
    </div>
</div>

